### ISSUE TITLE
EasyDict converting tuple to list

### ISSUE THREAD

**Issue by 9autilus** [makinacorpus/easydict#22]
While storing a tuple into the easydict, it is getting converted into a list. Is this by design?

Code to reproduce this behavior:

```python
# Python version 3.6.8, easydict version 1.9, Windows OS
from easydict import EasyDict

d = dict()
d['my_tuple'] = (1, 2)
print(type(d['my_tuple']))
# Prints as expected: <class 'tuple'>

ed = EasyDict()
ed['my_tuple'] = (1, 2)
print(type(ed['my_tuple']))
# Prints unexpected: <class 'list'>

ed['my_set'] = {1, 2}
print(type(ed['my_set']))
# Prints as expected: <class 'set'>
```

With thanks to contributors for their work.

**Comment by sumukhbarve** [comment]
Hi @govindnh4cl,

The conversion from `tuple` to `list` appears to be by design. Here's the relevant code-snippet:
```py
def __setattr__(self, name, value):
        if isinstance(value, (list, tuple)):
            value = [self.__class__(x)
                     if isinstance(x, dict) else x for x in value]
        elif isinstance(value, dict) and not isinstance(value, self.__class__):
            value = self.__class__(value)
        super(EasyDict, self).__setattr__(name, value)
        super(EasyDict, self).__setitem__(name, value)
```
The `if` branch treats instances of `list` and `tuple` the same; a list-comprehension is used in either case.

If you're looking for tuples to be treated differently, check out [Dotsi](https://github.com/polydojo/dotsi).

Regards,
Sumukh
